server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/groq_db?useSSL=false&serverTimezone=UTC
    username: integrador
    password: integrador123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai
  model: llama-3.1-8b-instant
  temperature: 0.3
